services:
  server:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    environment:
      PORT: 5174
      ASSETS_ROOT: /assets
    volumes:
      - ./assets:/assets:ro
    expose:
      - "5174"
  web:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    depends_on:
      - server
    ports:
      - "8080:80"
